[2024-04-27T08:51:18.767+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-27T08:51:18.807+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tweets_dag_v2.init_tweets_db scheduled__2024-04-26T00:00:00+00:00 [queued]>
[2024-04-27T08:51:18.819+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tweets_dag_v2.init_tweets_db scheduled__2024-04-26T00:00:00+00:00 [queued]>
[2024-04-27T08:51:18.819+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 6
[2024-04-27T08:51:18.839+0000] {taskinstance.py:2327} INFO - Executing <Task(PostgresOperator): init_tweets_db> on 2024-04-26 00:00:00+00:00
[2024-04-27T08:51:18.850+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'tweets_dag_v2', 'init_tweets_db', 'scheduled__2024-04-26T00:00:00+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/twitter_data_dag.py', '--cfg-path', '/tmp/tmp81oe9oof']
[2024-04-27T08:51:18.853+0000] {standard_task_runner.py:91} INFO - Job 4: Subtask init_tweets_db
[2024-04-27T08:51:18.857+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=384) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-04-27T08:51:18.858+0000] {standard_task_runner.py:63} INFO - Started process 416 to run task
[2024-04-27T08:51:18.915+0000] {task_command.py:426} INFO - Running <TaskInstance: tweets_dag_v2.init_tweets_db scheduled__2024-04-26T00:00:00+00:00 [running]> on host cd57c070245a
[2024-04-27T08:51:19.004+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='stan' AIRFLOW_CTX_DAG_ID='tweets_dag_v2' AIRFLOW_CTX_TASK_ID='init_tweets_db' AIRFLOW_CTX_EXECUTION_DATE='2024-04-26T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-26T00:00:00+00:00'
[2024-04-27T08:51:19.006+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-27T08:51:19.020+0000] {sql.py:276} INFO - Executing: CREATE TABLE IF NOT EXISTS positive_tweets (
    id SERIAL PRIMARY KEY,
    roberta_neg NUMERIC,
    roberta_neu NUMERIC,
    roberta_pos NUMERIC,
    author VARCHAR(50),
    content TEXT,
    date_time TIMESTAMP,
    number_of_likes INTEGER,
    number_of_shares INTEGER
);

CREATE TABLE IF NOT EXISTS negative_tweets (
    id SERIAL PRIMARY KEY,
    roberta_neg NUMERIC,
    roberta_neu NUMERIC,
    roberta_pos NUMERIC,
    author VARCHAR(50),
    content TEXT,
    date_time TIMESTAMP,
    number_of_likes INTEGER,
    number_of_shares INTEGER
);

CREATE TABLE IF NOT EXISTS neutral_tweets (
    id SERIAL PRIMARY KEY,
    roberta_neg NUMERIC,
    roberta_neu NUMERIC,
    roberta_pos NUMERIC,
    author VARCHAR(50),
    content TEXT,
    date_time TIMESTAMP,
    number_of_likes INTEGER,
    number_of_shares INTEGER
);

TRUNCATE TABLE positive_tweets;
TRUNCATE TABLE negative_tweets;
TRUNCATE TABLE neutral_tweets;

[2024-04-27T08:51:19.028+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-27T08:51:19.037+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 277, in execute
    hook = self.get_db_hook()
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 188, in get_db_hook
    return self._hook
           ^^^^^^^^^^
  File "/usr/local/lib/python3.12/functools.py", line 995, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 150, in _hook
    conn = BaseHook.get_connection(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 519, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `tweets_localhost` isn't defined
[2024-04-27T08:51:19.042+0000] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=tweets_dag_v2, task_id=init_tweets_db, execution_date=20240426T000000, start_date=20240427T085118, end_date=20240427T085119
[2024-04-27T08:51:19.052+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 4 for task init_tweets_db (The conn_id `tweets_localhost` isn't defined; 416)
[2024-04-27T08:51:19.073+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-04-27T08:51:19.086+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/models/baseoperator.py:1296 AirflowProviderDeprecationWarning: Call to deprecated class PostgresOperator. (Please use `***.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.Also, you can provide `hook_params={'schema': <database>}`.)
[2024-04-27T08:51:19.100+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-27T08:51:19.103+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
