[2024-04-27T09:08:42.207+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-27T09:08:42.237+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tweets_dag_v2.execute_python_script manual__2024-04-27T09:08:30.690537+00:00 [queued]>
[2024-04-27T09:08:42.246+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tweets_dag_v2.execute_python_script manual__2024-04-27T09:08:30.690537+00:00 [queued]>
[2024-04-27T09:08:42.248+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 6
[2024-04-27T09:08:42.263+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): execute_python_script> on 2024-04-27 09:08:30.690537+00:00
[2024-04-27T09:08:42.272+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'tweets_dag_v2', 'execute_python_script', 'manual__2024-04-27T09:08:30.690537+00:00', '--job-id', '67', '--raw', '--subdir', 'DAGS_FOLDER/twitter_data_dag.py', '--cfg-path', '/tmp/tmp_gpyrvr_']
[2024-04-27T09:08:42.273+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=1962) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-04-27T09:08:42.274+0000] {standard_task_runner.py:91} INFO - Job 67: Subtask execute_python_script
[2024-04-27T09:08:42.275+0000] {standard_task_runner.py:63} INFO - Started process 2051 to run task
[2024-04-27T09:08:42.322+0000] {task_command.py:426} INFO - Running <TaskInstance: tweets_dag_v2.execute_python_script manual__2024-04-27T09:08:30.690537+00:00 [running]> on host cd57c070245a
[2024-04-27T09:08:42.401+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='stan' AIRFLOW_CTX_DAG_ID='tweets_dag_v2' AIRFLOW_CTX_TASK_ID='execute_python_script' AIRFLOW_CTX_EXECUTION_DATE='2024-04-27T09:08:30.690537+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-27T09:08:30.690537+00:00'
[2024-04-27T09:08:42.402+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-27T09:08:42.420+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-27T09:08:42.420+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/extract_transform.py", line 29, in roberta_classifier
    tweets = pd.read_csv("./tweets.csv")
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 948, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 611, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1448, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1705, in _make_engine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 863, in get_handle
    handle = open(
             ^^^^^
FileNotFoundError: [Errno 2] No such file or directory: './tweets.csv'
[2024-04-27T09:08:42.432+0000] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=tweets_dag_v2, task_id=execute_python_script, execution_date=20240427T090830, start_date=20240427T090842, end_date=20240427T090842
[2024-04-27T09:08:42.443+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 67 for task execute_python_script ([Errno 2] No such file or directory: './tweets.csv'; 2051)
[2024-04-27T09:08:42.489+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-04-27T09:08:42.530+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-27T09:08:42.532+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
