[2024-05-06T07:04:13.096+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-06T07:04:13.157+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tweets_dag_v4.init_tweets_db scheduled__2024-05-02T00:00:00+00:00 [queued]>
[2024-05-06T07:04:13.170+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tweets_dag_v4.init_tweets_db scheduled__2024-05-02T00:00:00+00:00 [queued]>
[2024-05-06T07:04:13.171+0000] {taskinstance.py:2303} INFO - Starting attempt 6 of 8
[2024-05-06T07:04:13.198+0000] {taskinstance.py:2327} INFO - Executing <Task(PostgresOperator): init_tweets_db> on 2024-05-02 00:00:00+00:00
[2024-05-06T07:04:13.216+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=2341) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-06T07:04:13.214+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'tweets_dag_v4', 'init_tweets_db', 'scheduled__2024-05-02T00:00:00+00:00', '--job-id', '48', '--raw', '--subdir', 'DAGS_FOLDER/twitter_data_dag.py', '--cfg-path', '/tmp/tmpvr69dfzx']
[2024-05-06T07:04:13.219+0000] {standard_task_runner.py:63} INFO - Started process 2448 to run task
[2024-05-06T07:04:13.219+0000] {standard_task_runner.py:91} INFO - Job 48: Subtask init_tweets_db
[2024-05-06T07:04:13.306+0000] {task_command.py:426} INFO - Running <TaskInstance: tweets_dag_v4.init_tweets_db scheduled__2024-05-02T00:00:00+00:00 [running]> on host bbc51d156390
[2024-05-06T07:04:13.442+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='stan' AIRFLOW_CTX_DAG_ID='tweets_dag_v4' AIRFLOW_CTX_TASK_ID='init_tweets_db' AIRFLOW_CTX_EXECUTION_DATE='2024-05-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='6' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-02T00:00:00+00:00'
[2024-05-06T07:04:13.444+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-06T07:04:13.475+0000] {sql.py:276} INFO - Executing: CREATE TABLE IF NOT EXISTS positive_tweets (
    id SERIAL PRIMARY KEY,
    roberta_neg NUMERIC,
    roberta_neu NUMERIC,
    roberta_pos NUMERIC,
    author VARCHAR(50),
    content TEXT,
    date_time TIMESTAMP,
    number_of_likes INTEGER,
    number_of_shares INTEGER
);

CREATE TABLE IF NOT EXISTS negative_tweets (
    id SERIAL PRIMARY KEY,
    roberta_neg NUMERIC,
    roberta_neu NUMERIC,
    roberta_pos NUMERIC,
    author VARCHAR(50),
    content TEXT,
    date_time TIMESTAMP,
    number_of_likes INTEGER,
    number_of_shares INTEGER
);

CREATE TABLE IF NOT EXISTS neutral_tweets (
    id SERIAL PRIMARY KEY,
    roberta_neg NUMERIC,
    roberta_neu NUMERIC,
    roberta_pos NUMERIC,
    author VARCHAR(50),
    content TEXT,
    date_time TIMESTAMP,
    number_of_likes INTEGER,
    number_of_shares INTEGER
);

TRUNCATE TABLE positive_tweets;
TRUNCATE TABLE negative_tweets;
TRUNCATE TABLE neutral_tweets;

[2024-05-06T07:04:13.493+0000] {base.py:84} INFO - Using connection ID 'tweets_localhost' for task execution.
[2024-05-06T07:04:13.511+0000] {base.py:84} INFO - Using connection ID 'tweets_localhost' for task execution.
[2024-05-06T07:04:13.528+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-06T07:04:13.529+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 282, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 397, in run
    with closing(self.get_conn()) as conn:
                 ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/postgres/hooks/postgres.py", line 161, in get_conn
    self.conn = psycopg2.connect(**conn_args)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: connection to server at "host.docker.internal" (192.168.65.254), port 54321 failed: FATAL:  database "tweets" does not exist

[2024-05-06T07:04:13.544+0000] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=tweets_dag_v4, task_id=init_tweets_db, execution_date=20240502T000000, start_date=20240506T070413, end_date=20240506T070413
[2024-05-06T07:04:13.563+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 48 for task init_tweets_db (connection to server at "host.docker.internal" (192.168.65.254), port 54321 failed: FATAL:  database "tweets" does not exist
; 2448)
[2024-05-06T07:04:13.595+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-06T07:04:13.615+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/models/baseoperator.py:1296 AirflowProviderDeprecationWarning: Call to deprecated class PostgresOperator. (Please use `***.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.Also, you can provide `hook_params={'schema': <database>}`.)
[2024-05-06T07:04:13.638+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-06T07:04:13.640+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
